=== SergiSaya96/tfg/trunk/src/xml/dynamixel_motor_cfg_file.xsd
<?xml version="1.0"?>

<!--

file      : dynamixel_cfg_file.xsd 
author    : Sergi Hernandez Juan (shernand@iri.upc.edu)
copyright : not copyrighted - public domain

-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:simpleType name="alarm_t">
     <xsd:restriction base="xsd:string">
        <xsd:enumeration value="instruction_error"/>
        <xsd:enumeration value="overload_error"/>
        <xsd:enumeration value="checksum_error"/>
        <xsd:enumeration value="range_error"/>
        <xsd:enumeration value="overheating_error"/>
        <xsd:enumeration value="angle_limit_error"/>
        <xsd:enumeration value="input_voltage_error"/>
     </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="dynamixel_motor_config_t">
    <xsd:sequence>
      <xsd:element name="alarm_shtdwn" type="xsd:unsignedByte">
      </xsd:element>
      <xsd:element name="max_angle" type="xsd:float">
      </xsd:element>
      <xsd:element name="min_angle" type="xsd:float">
      </xsd:element>
      <xsd:element name="temp_limit" type="xsd:int">
      </xsd:element>
      <xsd:element name="max_voltage" type="xsd:float">
      </xsd:element>
      <xsd:element name="min_voltage" type="xsd:float">
      </xsd:element>
      <xsd:element name="max_torque" type="xsd:float">
      </xsd:element>
      <xsd:element name="cw_comp_margin" type="xsd:unsignedByte">
      </xsd:element>
      <xsd:element name="ccw_comp_margin" type="xsd:unsignedByte">
      </xsd:element>
      <xsd:element name="cw_comp_slope" type="xsd:unsignedByte">
      </xsd:element>
      <xsd:element name="ccw_comp_slope" type="xsd:unsignedByte">
      </xsd:element>
      <xsd:element name="punch" type="xsd:unsignedByte">
      </xsd:element>
      <xsd:element name="kp" type="xsd:unsignedByte">
      </xsd:element>
      <xsd:element name="ki" type="xsd:unsignedByte">
      </xsd:element>
      <xsd:element name="kd" type="xsd:unsignedByte">
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:element name="dynamixel_motor_config" type="dynamixel_motor_config_t">
  </xsd:element>

</xsd:schema>

=== SergiSaya96/tfg/trunk/src/xml/dyn_servo_config.xml
<?xml version="1.0"?>

<dynamixel_motor_config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="dynamixel_motor_cfg_file.xsd">

  <alarm_shtdwn>4</alarm_shtdwn>
  <min_angle>-125</min_angle>
  <max_angle>125</max_angle>
  <temp_limit>85</temp_limit>
  <max_voltage>19</max_voltage>
  <min_voltage>6</min_voltage>
  <max_torque>100</max_torque>
  <cw_comp_margin>0</cw_comp_margin>
  <ccw_comp_margin>0</ccw_comp_margin>
  <cw_comp_slope>32</cw_comp_slope>
  <ccw_comp_slope>32</ccw_comp_slope>
  <punch>32</punch>
  <kp>0</kp>
  <ki>0</ki>
  <kd>0</kd>
</dynamixel_motor_config>
